name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install backend deps
        run: |
          cd backend
          npm ci
  - name: Install frontend deps
        run: |
          cd frontend
          npm ci
          npx playwright install --with-deps
      - name: Start backend
        run: |
          cd backend
          nohup npm start &
      - name: Start frontend
        run: |
          cd frontend
          nohup npm run dev &
          sleep 5
      - name: Run Playwright tests
        run: |
          npm run test:e2e || true
      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report
